import type { Property } from "@/types"

export const FALLBACK_PROPERTIES: Property[] = [
  {
    id: "1", title: "Consultorio M\u00e9dico Premium - Costa del Este",
    subtitle: "Espacio de 85m\u00b2 con vista panor\u00e1mica",
    description: "Excepcional consultorio m\u00e9dico ubicado en el exclusivo sector de Costa del Este. Este espacio de 85m\u00b2 ofrece una distribuci\u00f3n \u00f3ptima para la atenci\u00f3n de pacientes, con recepci\u00f3n, sala de espera, 3 consultorios privados y \u00e1rea administrativa. Cuenta con acabados de lujo, climatizaci\u00f3n central y vista panor\u00e1mica.",
    handle: "consultorio-medico-costa-del-este", thumbnail: null, images: [],
    price: 285000, currencyCode: "PAB", variantId: null, location: "Costa del Este, Ciudad de Panam\u00e1",
    area: "85", bedrooms: 3, bathrooms: 2, type: "consultorio", status: "disponible" as const,
    features: ["Recepci\u00f3n", "Sala de espera para 12 personas", "3 consultorios privados", "\u00c1rea administrativa", "Climatizaci\u00f3n central", "Estacionamiento para 2 veh\u00edculos", "Seguridad 24 horas", "Vista panor\u00e1mica"],
    category: "Consultorios", createdAt: "2025-01-15",
  },
  {
    id: "2", title: "Cl\u00ednica Dental - San Francisco",
    subtitle: "Equipada y lista para operar",
    description: "Cl\u00ednica dental completamente equipada en el coraz\u00f3n de San Francisco. Este espacio de 120m\u00b2 cuenta con 6 consultorios dentales, sala de Rayos X, \u00e1rea de esterilizaci\u00f3n, y oficina administrativa.",
    handle: "clinica-dental-san-francisco", thumbnail: null, images: [],
    price: 420000, currencyCode: "PAB", variantId: null, location: "San Francisco, Ciudad de Panam\u00e1",
    area: "120", bedrooms: 5, bathrooms: 3, type: "clinica", status: "disponible" as const,
    features: ["6 consultorios dentales", "Sala de Rayos X", "\u00c1rea de esterilizaci\u00f3n", "Sala de espera", "Oficina administrativa", "Equipo odontol\u00f3gico incluido"],
    category: "Cl\u00ednicas", createdAt: "2025-01-10",
  },
  {
    id: "3", title: "Centro M\u00e9dico - Obarrio",
    subtitle: "Oportunidad de inversi\u00f3n \u00fanica",
    description: "Excepcional oportunidad de inversi\u00f3n en el coraz\u00f3n de Obarrio. Este centro m\u00e9dico de 350m\u00b2 cuenta con 10 consultorios, farmacia, laboratorio cl\u00ednico y estacionamiento privado.",
    handle: "centro-medico-obarrio", thumbnail: null, images: [],
    price: 850000, currencyCode: "PAB", variantId: null, location: "Obarrio, Ciudad de Panam\u00e1",
    area: "350", bedrooms: 10, bathrooms: 6, type: "centro-medico", status: "disponible" as const,
    features: ["10 consultorios", "Farmacia interna", "Laboratorio cl\u00ednico", "Sala de espera amplia", "Estacionamiento para 8 veh\u00edculos", "Seguridad 24 horas", "Ascensor"],
    category: "Centros M\u00e9dicos", createdAt: "2024-12-20",
  },
  {
    id: "4", title: "Consultorio de Especialidades - Punta Pac\u00edfica",
    subtitle: "Vista al mar, ubicaci\u00f3n exclusiva",
    description: "Elegante consultorio de especialidades en una de las zonas m\u00e1s exclusivas de la ciudad. 95m\u00b2 con 2 consultorios privados, sala de espera y archivo cl\u00ednico.",
    handle: "consultorio-especialidades-punta-pacifica", thumbnail: null, images: [],
    price: 320000, currencyCode: "PAB", variantId: null, location: "Punta Pac\u00edfica, Ciudad de Panam\u00e1",
    area: "95", bedrooms: 2, bathrooms: 2, type: "consultorio", status: "disponible" as const,
    features: ["2 consultorios privados", "Sala de espera", "Archivo cl\u00ednico", "Ba\u00f1os privados", "Vista al mar", "Estacionamiento", "Climatizaci\u00f3n"],
    category: "Consultorios", createdAt: "2025-02-01",
  },
  {
    id: "5", title: "Edificio M\u00e9dico - V\u00eda Espa\u00f1a",
    subtitle: "7 consultorios en excelente ubicaci\u00f3n",
    description: "Imponente edificio m\u00e9dico en la transitada V\u00eda Espa\u00f1a. Con 500m\u00b2 distribuidos en 3 plantas, alberga 7 consultorios m\u00e9dicos, recepci\u00f3n central, elevador y estacionamiento.",
    handle: "edificio-medico-via-espana", thumbnail: null, images: [],
    price: 1200000, currencyCode: "PAB", variantId: null, location: "V\u00eda Espa\u00f1a, Ciudad de Panam\u00e1",
    area: "500", bedrooms: 7, bathrooms: 5, type: "centro-medico", status: "disponible" as const,
    features: ["7 consultorios", "Recepci\u00f3n central", "Sala de espera", "Elevador", "3 plantas", "Estacionamiento para 10 veh\u00edculos", "Seguridad 24h"],
    category: "Centros M\u00e9dicos", createdAt: "2024-11-15",
  },
  {
    id: "6", title: "Consultorio - El Cangrejo",
    subtitle: "Ideal para inicio de pr\u00e1ctica",
    description: "Acogedor consultorio en El Cangrejo, perfecto para profesionales que inician su pr\u00e1ctica independiente. 55m\u00b2 con un consultorio principal, sala de espera y ba\u00f1o privado.",
    handle: "consultorio-el-cangrejo", thumbnail: null, images: [],
    price: 150000, currencyCode: "PAB", variantId: null, location: "El Cangrejo, Ciudad de Panam\u00e1",
    area: "55", bedrooms: 1, bathrooms: 1, type: "consultorio", status: "disponible" as const,
    features: ["Consultorio principal", "Sala de espera", "Ba\u00f1o privado", "Climatizaci\u00f3n"],
    category: "Consultorios", createdAt: "2025-01-28",
  },
  {
    id: "7", title: "Cl\u00ednica de Imagenolog\u00eda - Bethania",
    subtitle: "Equipo de \u00faltima generaci\u00f3n incluido",
    description: "Moderna cl\u00ednica de imagenolog\u00eda en Bethania, completamente equipada con tecnolog\u00eda de punta.",
    handle: "clinica-imagenologia-bethania", thumbnail: null, images: [],
    price: 680000, currencyCode: "PAB", variantId: null, location: "Bethania, Ciudad de Panam\u00e1",
    area: "200", bedrooms: 4, bathrooms: 3, type: "clinica", status: "vendido" as const,
    features: ["Resonancia Magn\u00e9tica", "Rayos X digital", "Ultrasonido", "4 consultorios", "Sala de informes", "Recepci\u00f3n"],
    category: "Cl\u00ednicas", createdAt: "2024-10-05",
  },
  {
    id: "8", title: "Consultorio Oftalmol\u00f3gico - Ave Balboa",
    subtitle: "Vista al mar, consultorio especializado",
    description: "Prestigioso consultorio oftalmol\u00f3gico en la emblem\u00e1tica Avenida Balboa. 110m\u00b2 con 3 consultorios, sala de espera y oficina administrativa.",
    handle: "consultorio-oftalmologico-ave-balboa", thumbnail: null, images: [],
    price: 380000, currencyCode: "PAB", variantId: null, location: "Ave Balboa, Ciudad de Panam\u00e1",
    area: "110", bedrooms: 3, bathrooms: 2, type: "consultorio", status: "disponible" as const,
    features: ["3 consultorios", "Sala de espera", "Oficina administrativa", "Vista al mar", "Estacionamiento", "Climatizaci\u00f3n central"],
    category: "Consultorios", createdAt: "2025-02-10",
  },
  {
    id: "9", title: "Centro de Rehabilitaci\u00f3n - Clayton",
    subtitle: "Amplio espacio para fisioterapia",
    description: "Centro de rehabilitaci\u00f3n f\u00edsica en Clayton, con 280m\u00b2 dise\u00f1ados espec\u00edficamente para fisioterapia y medicina deportiva.",
    handle: "centro-rehabilitacion-clayton", thumbnail: null, images: [],
    price: 550000, currencyCode: "PAB", variantId: null, location: "Clayton, Ciudad de Panam\u00e1",
    area: "280", bedrooms: 4, bathrooms: 4, type: "clinica", status: "disponible" as const,
    features: ["Sala de ejercicios", "4 consultorios", "\u00c1rea de hidroterapia", "Vestidores", "Recepci\u00f3n", "Estacionamiento amplio", "Acceso para discapacitados"],
    category: "Cl\u00ednicas", createdAt: "2025-01-05",
  },
]

export function getFallbackByHandle(handle: string): Property | undefined {
  return FALLBACK_PROPERTIES.find((p) => p.handle === handle)
}
